### ISSUE TITLE
macOS UX improvements

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1080]
- turn on https://www.electronjs.org/docs/tutorial/dark-mode einschalten damit die macOS Title-Bar auch so dunkel ist wie der Rest (auch wenn macOS auf Light gestellt ist)
- use https://www.electronjs.org/docs/tutorial/recent-documents for native recent menu
- use https://www.electronjs.org/docs/tutorial/represented-file Natives Proxy Icon in the titlebar (together with filename), always matching current tab
- setDocumentEdited=true for active/not currently saved live traces (Cmd/Serial/...)
- menues on mac os: e.g. we need a  File > Open... including Shortcut. and preferences under `chipmunk`, not under `file`  (also "Plugins" and "Install cm tool" under "chipmunk")
appname in dock capitalized  -> Chipmunk.app

**Comment by DmitryAstafyev** [comment]
Hello, @marcmo 
Could you please give some more comment/information, about this:
```
setDocumentEdited=true for active/not currently saved live traces (Cmd/Serial/...)
```
It isn't clear, what do you want to see as result

**Comment by DmitryAstafyev** [comment]
I will join to this issue in scope of points, which can be done using macos only

**Comment by bzld** [comment]
Small but very helpful additional fix:

- Configure Chipmunk app metadata to accept text files (or all files?), so that you can open files by dragging them onto the Chipmunk dock icon, or by selecting it in the "Open With" Finder context menu.
 
(Quick googling sounds like this is a .plist thing: https://www.electronjs.org/docs/api/app#event-open-url-macos)

**Comment by DmitryAstafyev** [comment]
> Small but very helpful additional fix:
> 
> * Configure Chipmunk app metadata to accept text files (or all files?), so that you can open files by dragging them onto the Chipmunk dock icon, or by selecting it in the "Open With" Finder context menu.
> 
> (Quick googling sounds like this is a .plist thing: https://www.electronjs.org/docs/api/app#event-open-url-macos)

Would you mind if I will exclude it into the standalone issue (feature request)?

**Comment by DmitryAstafyev** [comment]
I would close this issue as soon as in general it was resolved. As for "Open With", we are not sure, it's a good idea to assign chipmunk with any type of files as soon as chipmunk portable solution. But we always can create a standalone issue for that to have a standalone discussion
