### ISSUE TITLE
Chart display of scientific numbers having small scale.

### ISSUE THREAD

**Issue by to-scho** [esrlabs/chipmunk#1166]
**Prerequisites**
1st thanks for this great program!

When trying to visualize trace numbers having a very small scale e.g. 2.993736e-07 (search by "number:\s([-+]?[0-9]*.?[0-9]+([eE][-+]?[0-9]+)?)") the automated and fixed scale of the chart fails to have a proper visualization. Chart numbers are correct when I Mose over. Issue is that there seems to be a value (-1,1) at the beginning inserted and (...,-1) at the end that scales the chart to +-1.0 which makes the real data to appear as a fast line only.

affected version:
2.16.5

make sure to check this before filing an issue:

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**

-Manual chart scales in options of a chart that are also saved within filters
-Alternative, add offset and scale value applied to chart data before display
-Optionally (wish list), zoom chart by selecting rectangular area with the mouse
-Optionally (wish list), auto zoom chart to values of current time area

**Potential Workaround**
None

**More Information**

here you can supply screenshots or just add more details
![image](https://user-images.githubusercontent.com/30016396/116860594-178d9980-ac02-11eb-8c07-1e59d51074ca.png)

**Comment by DmitryAstafyev** [comment]
@to-scho Thanks for issue. Can you please provide us with an example of data? To make it possible for us to reproduce and see the same "picture" as you see.

**Comment by to-scho** [comment]
Sure, here is the trace:
[for_chipmunk.log](https://github.com/esrlabs/chipmunk/files/6413960/for_chipmunk.log)

Search by "number:\s([-+]?[0-9]*.?[0-9]+([eE][-+]?[0-9]+)?)"

By the way, some shortcut for regular Expression bathing any number "([-+]?[0-9]*.?[0-9]+([eE][-+]?[0-9]+)?)" would be super nice ;-)

**Comment by DmitryAstafyev** [comment]
Covered with 2.18.0 (https://github.com/esrlabs/chipmunk/releases/tag/2.18.0)
