### ISSUE TITLE
Restarting the OS does leak chipmunk shortcuts into the system

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1170]
version: 2.16.5
OS: Mac OS

when I restart Mac OS and chipmunk was open but not focused, chipmunk creates system wide keyboard shortcuts even though it was not focused after the restart.
=> `CMD`+`T`, `CMD`+`W` a.s.o. are not working!

**Comment by DmitryAstafyev** [comment]
isn't actual for chipmunk 3
