### ISSUE TITLE
Chart: support huge amount of data

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1180]
The current implementation of the chart applies an income dataset as it is. For example, if the dataset has 1 000 000 points - chartjs will get whole dataset with all 1M points. Sure it isn't nice for performance. 

But as soon as user cannot have screen width with 1M px, it doesn't make sense to send all 1M points to charts. 

We can scale data somehow based on available width of chart. Let's say if width of chart is 600px, we need just 600 points to draw chart. 

To discuss:
- Ways of scale chart (ex: by min, by max, by middle)
- Ways of rendering scaled chart

**Comment by fur-gan** [comment]
Resolved in Chipmunk 3
- Chart shows scaled map if dataset too big
- Back-End provides a scaled map of the dataset in the requested size
