### ISSUE TITLE
Error message when loading a file with chart

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#1182]
**Describe the issue**

Getting an error message when a file with a chart is loaded in the console

**Steps to Reproduce**

1. open logfile
2. create chart in `search manager` with regex
3. close `Chipmunk`
4. open `Chipmunk`
5. open previously opened logfile

**Failure Logs**

![image](https://user-images.githubusercontent.com/56543045/119365757-8cf40380-bcb0-11eb-81f7-9ad64aacce05.png)

**Comment by DmitryAstafyev** [comment]
I cannot reproduce it on windows/mac/linux

**Comment by fur-gan** [comment]
Seems like this was also an issue of my internal settings. It's related to the path not being recognized with '/' and works as soon as I replace the '/' with '\'
