### ISSUE TITLE
Refactor relative path in all TS files 

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#1203]
Refactor the current solution where all the relative paths don't have `../../../../` anymore in it and make the code more human-readable

Reference: https://decembersoft.com/posts/say-goodbye-to-relative-paths-in-typescript-imports/

**Comment by DmitryAstafyev** [comment]
It should not be a standalone task. We should create a more complex plan of deep review/refactor of the front-end part.
