### ISSUE TITLE
Allow timestamp format to not include YYYY/MM/DD

### ISSUE THREAD

**Issue by nmcgregor403** [esrlabs/chipmunk#1241]
Some logs have no YYYY/MM/DD:
![image](https://user-images.githubusercontent.com/90108446/133497508-dce14df4-1dc5-4566-94d1-be0deff8d56d.png)
We can include a default year in the merge menu but not a default Day and Month.

**Comment by DmitryAstafyev** [comment]
@nmcgregor403 thanks for the issue report, I've put it into the queue. We will care about it.

**Comment by DmitryAstafyev** [comment]
chipmunk 3 doesn't include merge & time/date detecting functionality.
