### ISSUE TITLE
Commenting doesn't work

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#1251]
**Describe the issue**

The `Comment` functionality doesn't work in a specific case / nothing happens

**Steps to Reproduce**

1. Mark lines starting from a high line number and scroll upwards (outside of the currently visible lines)
2. Right-click and select `Comment`

**Comment by DmitryAstafyev** [comment]
Unfortunately, we can create a comment on only visible selection. Well, I've added checks before context-menu would be opened to hide comment item on not fully visible selections
