### ISSUE TITLE
Editing a search is impossible

### ISSUE THREAD

**Issue by MortronMeymo** [esrlabs/chipmunk#1282]
**Describe the issue**

Ever since the search was changed from being a simple textbox editing the search afterwards has become impossible.

**Steps to Reproduce**

Enter a search, make a typo, hit enter, try to correct typo, realize there is no way to do it other than reentering the search from hand.

**Environment**
Version: 2.22.6
Platform: linux(x64) / Linux / 20.04.1
Electron: 10.2.0
Electron Rebuild: 2.3.4
ToolKit: 1.4.1
IPC: 0.0.51
Chipmunk Material: 1.2.17
Angular: 12.2.9
Angular Material: 12.2.9

**Comment by DmitryAstafyev** [comment]
Hello @MortronMeymo 

Thanks for your report

With the last [release](https://github.com/esrlabs/chipmunk/releases/tag/2.22.9) we've adjusted search-input-logic.
As soon as you have some active search (you see blue shortcut) you can just press "Backspace" and you will be dropped into correction/edit mode.

Please reopen this issue, if last release still doesn't resolve your issue
