### ISSUE TITLE
Opening multiple files from File-->Open File menu

### ISSUE THREAD

**Issue by liquidchair** [esrlabs/chipmunk#1296]
**Prerequisites**

affected version: 2.22.9

make sure to check this before filing an issue:

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**

It would be great if it would be available the possibility to open many files from File-->Open File menu and they open in the separate tab of the application. At the current moment for each file, you have to do it separately.

**More Information**

Version: 2.22.9
Platform: win32(x64) / Windows_NT / 10.0.19043
Electron: 10.2.0
Electron Rebuild: 2.3.4
ToolKit: 1.4.1
IPC: 0.0.51
Chipmunk Material: 1.2.18
Angular: 12.2.10
Angular Material: 12.2.10

**Comment by fur-gan** [comment]
Hi @liquidchair, thank you for opening this issue. Opening multiple files from the application menu is now available on version `2.24.1`. 🎉 

Here's a short demonstration of it:
![application_menu](https://user-images.githubusercontent.com/56543045/145621740-9dfc58c1-4385-4af9-ab92-ae4ed19c9393.gif)

We also do support drag and drop of multiple files resulting in the same dialog window shown here:
![drag_and_drop](https://user-images.githubusercontent.com/56543045/145622147-c4de1040-dfc9-4d2b-8e69-8011ecf87134.gif)
