### ISSUE TITLE
make it possible to "cut" the input

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#130]
when investigating a large log file it sometimes is easier to cut of some time spans. e.g. cut out all events that are older then 1h.
add a menu item "cut-off head" and "cut-off tail" that will result in the cursor displaying a scissors symbol. on click between 2 lines (shown with a marker) the content above or below should be discarded

**Comment by DmitryAstafyev** [comment]
We have very similar functionality. Users can select content and export it into a file. And open such a file after.
