### ISSUE TITLE
Regex mechanism changed or broken

### ISSUE THREAD

**Issue by vladirupanov** [esrlabs/chipmunk#1319]
**Prerequisites**

affected version: 
Version: 2.26.1
Platform: linux(x64) / Linux / 18.04.1

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

Filters with "wildcards" like  `DR[\s\S]+STAT[\s\S]+transp_delay:\s(\d+)[\s]+us` do not match anymore

**Steps to Reproduce**

Open a DLT file with verbose messages and extended header.
For any message with AppId `APP` and CtxId `CTX` enter a filter `APP[\s\S]+CTX`
Enjoy empty match

_NOTE: still works fine in the following env
Version: 2.18.5
Platform: darwin(x64) / Darwin / 19.6.0
Electron: 10.2.0
Electron Rebuild: 2.3.4
ToolKit: 1.3.16
IPC: 0.0.51
Chipmunk Material: 1.2.11
Angular: 11.1.1
Angular Material: 11.1.1_

**Environment**

Version: 2.26.1
Platform: linux(x64) / Linux / 18.04.1
Electron: 10.2.0
Electron Rebuild: 2.3.4
ToolKit: 1.4.1
IPC: 0.0.51
Chipmunk Material: 1.2.18
Angular: 12.2.10
Angular Material: 12.2.10

**Failure Logs**

Unfortunately not enough knowledge is provided as to the log contents / location. Please contact @vladirupanov to get more info.

**Comment by marcmo** [comment]
Hi @vladirupanov !
I've tested with 2.26.3 and could not reproduce it:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/99541/219106488-41785eb3-26ae-409f-a5dc-d187208f3c8b.png">
could you please confirm that is happening for you?

Maybe you noticed we are hard at work with `chipmunk 3`. It is still in beta but will soon replace chipmunk 2.
you are most welcome to test it and tell us about your impressions. Thanks ❤️
