### ISSUE TITLE
Quick actions buttons not working

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#1492]
**Describe the issue**

Clicking on "DLT Streaming" or "Text  Streaming" does nothing.

**Environment**

Version 3.0.7 / 3.0.8 / 3.0.9

**Failure Logs**

In the developer-tools console the following error message appears: `Fail to open DLT stream; error: Fail to find initial component "app-tabs-source-dltstream"`

**Comment by DmitryAstafyev** [comment]
Maybe in devtools console, some other logs are present? 
Initial component - component, which can be created dynamically. All such components have decorator `@Initial`, like here
```
@Component({
    selector: 'app-tabs-source-dltstream',
    templateUrl: './template.html',
    styleUrls: ['./styles.less'],
})
@Initial()
@Ilc()
export class TabSourceDltStream { .... }
```
If we have error `Fail to find initial component`, it means the declaration of the target component wasn't triggered.

**Comment by DmitryAstafyev** [comment]
windows?

**Comment by fur-gan** [comment]
> windows?

Tested both on Windows and Linux

**Comment by fur-gan** [comment]
> Maybe in devtools console, some other logs are present?

No other messages. Only this one error message when you click the button.

> If we have error `Fail to find initial component`, it means the declaration of the target component wasn't triggered.

Yes, need to check why that is

**Comment by DmitryAstafyev** [comment]
Rebase please your solution. Now there are should be additional logs. Could you please post it here

**Comment by DmitryAstafyev** [comment]
okay. I can confirm a bug. It actually only for the client in production mode. Looks like angular compile optimize it too much )
