### ISSUE TITLE
Bugs & Quirks Chipmunk 3

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1543]
## Suggestions
- [x] S.1. Cmd+T should maybe switch to the home-tab
- [x] S.2. Activate should only be displayed if not activated yet
<img width="230" alt="Activate" src="https://user-images.githubusercontent.com/99541/204241937-e6819132-8e03-4217-b2b1-db7ca98d5314.png">

- [x] S.3. The disabled items should look the same but just greyed out
- [x] S.4. the cross symbol should either be a button or be removed
<img width="690" alt="Connection" src="https://user-images.githubusercontent.com/99541/204242004-2ef0ef53-09b8-4219-b10c-bbfbd58cdc74.png">

- [ ] S.5. Developer settings need to be removed
- [ ] S.6. reload and force reload should be removed

## Bugs
- [x] B.1. keyboard mapping not removed when leaving chipmunk
- [x] B.2. Flash-of-unstyled content
- [x] B.3. last tab not recognizable as a tab if not selected
<img width="477" alt="access huge log" src="https://user-images.githubusercontent.com/99541/204241810-f79c11c9-5145-4d33-ad3c-957eb9a95b45.png">

- [x] B.4. right-click on selection de-selects everything but the current word
- [x] B.5. export not possible in menu
- [x] B.6. export all search results -> resulting file has no ending (should be txt) and is empty
- [x] B.7. raw-export of all search results -> empty file
- [x] B.8. Cmd+`?` does not show shortcuts on mac
- [ ] B.9. clicking on the search-result bar does not jump to position
<img width="100" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/99541/204241906-f04ac471-6421-4eb8-a375-99c0e4a735d9.png">

- [x] B.10. enter will only work once
<img width="301" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/99541/204241984-ba0fc012-3319-48c8-ae98-b32c0041fa57.png">

- [x] B.11. and then the search options are not visible anymore (capital,regex, …)
- [x] B.12. cannot see a “desc” field - Streams
- [x] B.13. removing multicast sections not possible - UDP Streams
- [x] B.14. streams in general do not seem to work
<img width="378" alt="Session doesn't exist" src="https://user-images.githubusercontent.com/99541/204242033-b4bd883c-9c6d-41bd-b5db-fc74b75c28f6.png">

- [x] B.15. Settings button does not work
<img width="104" alt="Settings" src="https://user-images.githubusercontent.com/99541/204242058-fe4bc89d-e281-4620-b8ef-13e0efddaa4a.png">

- [ ] B.16. selecting timezones does not work
- [x] B.17. About menu does not work

## Questions:
- [ ] Q.1. what’s the difference ?
<img width="216" alt="Export All Search Result" src="https://user-images.githubusercontent.com/99541/204241873-3fa3e9c4-d51c-4a47-a079-21ee8ddad32d.png">

- [x] Q.2. what is “Show matches”?

**Comment by fur-gan** [comment]
About the points:

> Activate should only be displayed if not activated yet

Activate/Deactivate: Show or hide results only in `search` output (The checkbox on the left)
Enable/Disable: Show or hide coloring in the `main output` and show or hide results in the `search` output 


> What is “Show matches”?

Run a search with only the selected term in the `search` output (Not implemented yet)

**Comment by DmitryAstafyev** [comment]
> B.17. About menu does not work
Cannot confirm.

**Comment by DmitryAstafyev** [comment]
> B.8. Cmd+? does not show shortcuts on mac

we defined `?` (`shift + ?`) for it

**Comment by marcmo** [comment]
almost all done, rest will be moved to new issue
