### ISSUE TITLE
Chart view: scrolling and panning in main view

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1600]
Scroll and zoom needs to work in main part of chart view also.

Vertical position of mouse pointer needs to be visible in main chart view

Reference: developer tools chrome
<img width="463" alt="image" src="https://user-images.githubusercontent.com/99541/210813738-1d693238-8d46-4ff9-af2f-b1abad0ccd76.png">

**Comment by DmitryAstafyev** [comment]
done with 3.9.x
