### ISSUE TITLE
Add configuration section for command execution

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1602]
collapsable section is needed for the command environment
Should contain:
- Current working directory
- Environment variables
- Shell selection (bash/zsh/csh/...)

<img width="904" alt="image" src="https://user-images.githubusercontent.com/99541/210816931-121658ea-2a72-47c9-b3d3-86b5662cd150.png">

**Comment by DmitryAstafyev** [comment]
not actual since 3.9.x
