### ISSUE TITLE
Unable to Identify what several buttons do within the "SearchBar"

### ISSUE THREAD

**Issue by AWM-AllynJ** [esrlabs/chipmunk#1603]
**Prerequisites**

affected version:
Version: 2.26.3
Platform: darwin(x64) / Darwin / 22.1.0
Electron: 10.2.0
Electron Rebuild: 2.3.4
ToolKit: 1.4.1
IPC: 0.0.51
Chipmunk Material: 1.2.18
Angular: 12.2.10
Angular Material: 12.2.10

make sure to check this before filing an issue:

- [X] I checked the documentation and found no answer

- [X] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**
I would like to see the documentation updated to help identify what some of the Search Bar buttons "do" - Mousing over them does not give any type of tooltip.   Very limited trial and error does not help to identify what any of these buttons do either.  

**What should be added to support your usecase?**
Either a UI Tooltip when hovering over these buttons, or updated documentation to reflect what these buttons do.  

**More Information**

I am attaching a screenshot of the buttons in question
![Screenshot 2023-01-05 at 9 29 45 AM](https://user-images.githubusercontent.com/6547569/210819033-2efa77a9-4b02-4b45-a576-eab6e5b0605b.png)

**Comment by marcmo** [comment]
good input, thanks @AWM-AllynJ 
What those buttons mean:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/99541/211083611-1c27cefb-d1ba-42ca-a65d-9a48e7fc2453.png">
<img width="216" alt="image" src="https://user-images.githubusercontent.com/99541/211083655-1c348656-48fe-4f3f-8e35-9d6f83daf4ae.png">
<img width="197" alt="image" src="https://user-images.githubusercontent.com/99541/211083691-a2379969-053d-4c6c-a2e5-b262461cc2b4.png">

we need to add this tooltip (screenshots are from VS Code)

@AWM-AllynJ please note that we will probably only fix this in chipmunk 3 (which is currently in Beta)

**Comment by marcmo** [comment]
Fixed in 3.4.18
<img width="122" alt="image" src="https://user-images.githubusercontent.com/99541/212119622-5726da93-0d3d-4eff-b829-4e1c2b6ac6d7.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/99541/212119637-4255506a-f915-4745-84b8-80afccb43614.png">
<img width="214" alt="image" src="https://user-images.githubusercontent.com/99541/212120470-b88fd1a5-f6c8-4dea-b81d-cb687cbe0181.png">
