### ISSUE TITLE
Cmd + Q does not terminate chipmunk

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1608]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/99541/211056294-e5c3b0b5-30c3-4278-98c1-14796631ba1e.png">
needs shortcut like this:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/99541/211056431-6da20942-7903-4871-b6b2-c3c1c9f6cbea.png">

**Comment by DmitryAstafyev** [comment]
done with 3.9.x
