### ISSUE TITLE
Chipmunk Release 3 Countdown

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1779]
* [x] Add `CMD+Q` (`Ctrl-Q`) shortcut to quit chipmunk @DmitryAstafyev 
* [x] `CMD+Q` now works but shortcut should be visible in menu
<img width="184" alt="image" src="https://user-images.githubusercontent.com/99541/236801911-6a2ad7e7-e46c-4c4f-9c25-829d238ab173.png">

* [x] enable drag & drop in every situation @DmitryAstafyev 
* [x] serial port review
* [x] folder's reader issue (used for `ctrl + p`)
* [x] filter by extensions (attachment view)
* [x] tree view (folder's browser) on home screen
* [x] context menu for attachments not available anymore (show in trace etc.)
<img width="293" alt="image" src="https://user-images.githubusercontent.com/99541/236761076-fe1fc2cf-9be1-4004-ab2f-57b15393a036.png">

* [ ] move filter menu to top
<img width="490" alt="image" src="https://user-images.githubusercontent.com/99541/236763068-283818be-483e-4e01-a8ac-3eb070d17022.png">

* [ ] esc does not close window
<img width="335" alt="image" src="https://user-images.githubusercontent.com/99541/236771293-47e3561f-bf82-46cf-9531-4a868f234fd0.png">

* [x] executing command should be a one-click option (remove sub-menu)
<img width="189" alt="image" src="https://user-images.githubusercontent.com/99541/236771941-2171fe4f-27be-4498-a42c-24071adf10ac.png">

* [x] `/` needs to be pressed twice to focus on the search input
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/99541/236774642-1ab93943-005f-46c5-8f63-5ab950c92d4a.png">

* [x]   `esc` should exit the search input
* [x] markers not visible when search is active
<img width="761" alt="image" src="https://user-images.githubusercontent.com/99541/236802949-7f5b9825-193f-4c8b-a7e6-e75298b5e8e1.png">
 
* [x] settings is currently empty. for starters we should include the favorite folder 
<img width="1033" alt="image" src="https://github.com/esrlabs/chipmunk/assets/99541/3a7ee77d-c91a-48cf-b6b4-90e0b809e025">

* [x] in the search-input: arrow keys `up` and `down` do not select previous searches...should activate the history window
<img width="296" alt="image" src="https://github.com/esrlabs/chipmunk/assets/99541/b7fd14ef-60f8-4bcb-b77d-310fb377747a">

* [x] `cmd+p` does not select the first entry. Instead, it selects the entry that is "above" the cursor. => needs to select first entry, arrow up/down need to work
<img width="472" alt="image" src="https://github.com/esrlabs/chipmunk/assets/99541/060a9e32-9fa5-4efa-8852-fd4a53e397f1">

* [x] preset/history not rendered correctly and filters are missing in view
<img width="280" alt="image" src="https://github.com/esrlabs/chipmunk/assets/99541/6de4bc3c-d167-4669-80db-69dfb4f6c130">
<img width="275" alt="image" src="https://github.com/esrlabs/chipmunk/assets/99541/b2fa0f7f-1e43-4590-9b3e-1819222da9e0">

**Comment by DmitryAstafyev** [comment]
>  markers not visible when search is active
yes, it's the expected result. 
A user creates an active search (aka single search) and chipmunk **puts accents only** to this search; that's why all others are hidden.

**Comment by DmitryAstafyev** [comment]
> move filter menu to top

I would exclude it into standalone issue
