### ISSUE TITLE
Add export/import filters to menu

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1833]
also add it to the context menu for filters
<img width="227" alt="image" src="https://github.com/esrlabs/chipmunk/assets/99541/d3ab10aa-24de-4a79-8e75-cafe963d5cf6">

**Comment by DmitryAstafyev** [comment]
@sudeeptarlekar the general solutions would be:
- into context-menu (calls on any filter/chart) introduce item - `Export into File`
- by selecting it - opens dialog to select destination file
- by selecting of file - save all filters/charts/disabled into given file
