### ISSUE TITLE
Feature Request: Export to file without selection

### ISSUE THREAD

**Issue by joboesr** [esrlabs/chipmunk#1840]
**Prerequisites**

affected version:

make sure to check this before filing an issue:

- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**

When live-debugging via e.g. logcat/rogcat it´s cumbersome to export, as you have to select all lines and then right-click for exporting.
It would be very helpful to have "Export-All" option. 
Potentially a better selection process would also help, currently it´s difficult to select all, as you have to start the select, scroll, press shift and then click again and sometimes this is messed up or easy to mess up when there are 10k´s of lines.

**Potential Workaround**

**More Information**

**Comment by DmitryAstafyev** [comment]
done with #1856
