### ISSUE TITLE
Chipmunk3 missing column colorisation feature

### ISSUE THREAD

**Issue by sudeeptarlekar** [esrlabs/chipmunk#1852]
**Prerequisites**

affected version: 3

make sure to check this before filing an issue:

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**

In chipmunk2 user can add a color to particuar column but this feature is missing from Chipmunk3
![Screenshot 2023-07-13 at 2 09 34 PM](https://github.com/esrlabs/chipmunk/assets/23317691/f9525e3f-f3e0-4f83-85cd-31b1f561ec02)

**Comment by DmitryAstafyev** [comment]
consider please also #1628
