### ISSUE TITLE
Cannot find source id for file when loading multiple file with Concat from the Multiple Files dialog

### ISSUE THREAD

**Issue by Odyssey-Gaming** [esrlabs/chipmunk#1859]
**Prerequisites**
3.8.2
**Describe the issue**
We have a lot of smaller log files (10Mb) and have an issue opening 300 of them via the concat operation of the open files function.

I am getting the error
"Cannot find source id for file D:\XXXXX\XXXXXX.txt.324 with alias f7cd1797-03a7-4cd2-0eab8604a153"

**Steps to Reproduce**
1) Have a lot of log files (300 for me).  The file name pattern we have is xxxxxx-log.txt.324.
2) Select "Open File(s)" menu
3) Select all of the files in the file picker from step 1.  The "Multiple files" dialog should open
4) Click on the "Multiple files" dialog "Concat" action button
5) Error occurs

**Environment**
Windows 10 Enterprise - 10.0.19045
Chipmunk 3.8.2

**Failure Logs**

Please include any relevant log snippets or files here.

**Comment by DmitryAstafyev** [comment]
@Odyssey-Gaming thanks for reporting this. It happens because source_id is `u8` and as a result, we are limited to 255 files. We will switch it to `u16` and fix will be available with next release
