### ISSUE TITLE
Terminal commands on windows

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1916]
Terminal/console commands don't give output
Platform: windows
Command: `ping google.com -t`
Reported [here](https://habr.com/ru/articles/764936/#comment_26029918)

**Comment by DmitryAstafyev** [comment]
Cannot reproduce the issue on Windows 11. The commands bellow works fine
```
ping www.google.com
ping www.google.com -n 99999
ping www.google.com -t
```
Contacted an issuer for additional information.

**Comment by DmitryAstafyev** [comment]
I think a reason can be detected with chipmunk's logs. If an issuer will join to discussion, I would ask to give us logs from `~/.chipmunk/chipmunk.log` and `~/.chipmunk/chipmunk.indexer.log`

**Comment by Vinni37** [comment]
Hi. Win 10. Screenshot 
![image](https://github.com/esrlabs/chipmunk/assets/17575200/09f9faa0-96de-4d1a-8264-bc1d31eb610a)

**Comment by Vinni37** [comment]
Logs
[chipmunk.log](https://github.com/esrlabs/chipmunk/files/12818287/chipmunk.log)
[chipmunk.indexer.log](https://github.com/esrlabs/chipmunk/files/12818288/chipmunk.indexer.log)

**Comment by DmitryAstafyev** [comment]
@Vinni37 thanks much!

**Comment by DmitryAstafyev** [comment]
windows 10 tested... no issues.
But I've changed the language to Russian ;) and was able to reproduce the error. Well, it's a coding issue.

**Comment by DmitryAstafyev** [comment]
@Vinni37, it looks like your issue is related to UTF8 coding. At the current moment, we are supporting only UTF8. As far as I understand you are using Russian localization on windows. In this case the way around could be:

1. Open "Параметры"

![Screenshot from 2023-10-06 09-47-23](https://github.com/esrlabs/chipmunk/assets/12843747/a9e3fbc5-46ca-486e-b7d3-4b0c2ff06f49)

3. Go to "Язык и Время"

![Screenshot from 2023-10-06 09-47-54](https://github.com/esrlabs/chipmunk/assets/12843747/4830530d-1fe1-4337-b45f-759234f4de09)

5. Click on "Дисплей Windows" and scroll down

![Screenshot from 2023-10-06 09-48-12](https://github.com/esrlabs/chipmunk/assets/12843747/572cf495-543f-4154-be8e-9d9b0ba62c8b)

7. Go to "Административные языковые параметры"

9. Set English language for "Текущий язык программ, не поддерживающих Юникод"
![Screenshot from 2023-10-06 09-48-27](https://github.com/esrlabs/chipmunk/assets/12843747/a828c5ae-ac41-4ff8-afec-b3ec55f199e7)

**Comment by DmitryAstafyev** [comment]
@Vinni37 thanks again for the report. I'm closing this issue, because of a general has been created: #1921
