### ISSUE TITLE
Registration in repositories for package managers 

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1919]
Add chipmunk to:
- pacman (arch, manjaro)
- brew (mac)
- chocolatey (windows) - @sudeeptarlekar
- apt (ubuntu, debian) - @alfr1337 
- dnf (fedora)
- YaST (opensuse, redhat)
- dpkg (deepin)
- etc.

**Comment by AmmarAbouZor** [comment]
This would be great.
For Linux systems I would suggest going in cross-distribution package managers like Flatpak, Snap, Linuxbrew and Nix package manger, since they are available on every Linux distribution nowadays and they are easier to package

**Comment by DmitryAstafyev** [comment]
@AmmarAbouZor thanks for your suggestion... it really makes sense. We should start with this issue pretty soon. At the moment we are in a state of research of the most optimal way to organize it in a somehow automatic way.

**Comment by AmmarAbouZor** [comment]
@DmitryAstafyev I think it can be added to the release GitHub action. For Snaps there is already GitHub Actions for that. The [Neovide](https://github.com/neovide/neovide) Project has it built in their release Action.

For Flatpak (Main store is [Flathub](https://flathub.org/en)) and Nix it's possible to add them to the release action too since each publish consists of CLI commands.

**Comment by ZyX-II** [comment]
For winget (and initially chocolatey) I found [this](https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/) blog post which is old enough to be possibly outdated, so I checked actual repository of the project and found out that there still is [winget github action](https://github.com/dolthub/dolt/blob/c107df2bc2bf6b59e217c10d877fdf40932fa234/.github/workflows/cd-bump-winget.yaml), but nothing for chocolatey: developing of the [tool](https://github.com/majkinetor/au) referenced in the blog post stopped.
There is however [another project](https://github.com/Ellerbach/docfx-companion-tools) which managed to automate chocolatey, its latest release was 5 days ago and already in chocolatey. They also bothered to write [a blog post](https://mtirion.medium.com/publish-a-net-console-app-to-chocolatey-using-github-actions-29eaa60a8668) about that too.

Have not found anything conclusive for scoop though.

**Comment by DmitryAstafyev** [comment]
We will organize/manage distribution on a standalone repo: https://github.com/esrlabs/chipmunk-distribution to make it easier maintain

**Comment by DmitryAstafyev** [comment]
issue can be closed as soon as we have now: https://github.com/esrlabs/chipmunk-distribution ... all issues related to package managers should be addressed there
