### ISSUE TITLE
Update build sys: no clean way to rebuild platform

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1947]
Way to reproduce:
- change code in `platform`
- run `rake build:dev`

Result:
- changes aren't delivered into `holder` and `ts-binding`

Expectation:
- as soon as platform has been changed, it should be rebuild and delivered into `holder` and `ts-binding`
- `ts-binding` should be rebuilt with updated `platform`
- `holder` should be rebuilt with updated `platform`

Note: `client` linked directly to `platform` and doesn't require delivery action

Also, I've tried:
```
rake build_dev
rake electron:build_dev
rake platform:build
rake bindings:build
```

**Comment by DmitryAstafyev** [comment]
Logic / workflow:

```
code of platform updated
-> rebuild platform
-> delivery platform to
    - ts-binding
    - holder
-> rebuild ts-bindings
-> delivery ts-bindings to holder
-> rebuild client
-> delivery client to holder
-> rebuild holder
```

**Comment by marcmo** [comment]
what's the best way to check this? what file to change and then where to observe the consequences @DmitryAstafyev ?
