### ISSUE TITLE
multiple whitespaces get combined

### ISSUE THREAD

**Issue by flooo6297** [esrlabs/chipmunk#1949]
affected version: 3.9.22

Anytime multiple whitespaces are next to each other, they get combined. 
It doesn't matter if they're spaces or tabs, they will get combined
Check the following testfile. it containes spaces, tabs or both between the words 'test'.
[testfile.txt](https://github.com/esrlabs/chipmunk/files/13162840/testfile.txt)

it looks like this in chipmunk:
![image](https://github.com/esrlabs/chipmunk/assets/44530135/f95b45c4-53bc-453e-9d22-827a854b998a)

When the affected lines appear in a search, they are rendered correctly. Then it looks like this:
![image](https://github.com/esrlabs/chipmunk/assets/44530135/26079331-3b35-4a1b-90bb-164bf7bff86a)

**Comment by marcmo** [comment]
thanks for reporting! related to #1928
