### ISSUE TITLE
Selection is reset in the middle of one line

### ISSUE THREAD

**Issue by ikar49** [esrlabs/chipmunk#1953]
**Prerequisites**

affected version: 3.9.20 and newer

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

When i want with mouse select word its resetted after release mouse-key.
But i can correct select some lines.
But Chipmunk 3.9.19 works correctly.

I think it's related to #1932

**Steps to Reproduce**

1. select text in one line
1. release mouse-key

**Environment**

OS version: Windows 10 Enterprise 22H2 19045.3570
Chipmunk: 3.9.20, 3.9.21, 3.9.22 and 3.10.0

**Failure Logs**

I haven't logs, but i have screencasts:
[Chipmunk 3.9.19](https://github.com/esrlabs/chipmunk/assets/1428838/0b00c7a0-9075-4cb1-ada0-47f19d3b7c85)
[Chipmunk 3.9.20](https://github.com/esrlabs/chipmunk/assets/1428838/781ebe6a-1884-48cd-859e-d97b47ff33c6)
[Chipmunk 3.9.22](https://github.com/esrlabs/chipmunk/assets/1428838/62a8e38e-1aef-4649-b2b2-452efd2a68f3)
[Chipmunk 3.10.0](https://github.com/esrlabs/chipmunk/assets/1428838/751de934-5ffd-4589-b9e5-aa1a09788b75)

**Comment by DmitryAstafyev** [comment]
@ikar49 Hello, thanks for the report! We will check it and fix it as soon as possible.

**Comment by DmitryAstafyev** [comment]
@ikar49 we released [3.10.1](https://github.com/esrlabs/chipmunk/releases/tag/3.10.1). For now it's pre-release (chipmunk will not update from it). It will go into release in 1-2 days after full cross-platform test cycle.
Once again thanks for your report

**Comment by ikar49** [comment]
@DmitryAstafyev so fast!? You are amazing!
Thank you for your product!
