### ISSUE TITLE
Contribution.md Instructions are outdated 

### ISSUE THREAD

**Issue by AmmarAbouZor** [esrlabs/chipmunk#1959]
**Prerequisites**

affected version: Current Master 3.10.2

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

The build instructions in `contribution.ms` seems to be outdated.
For Example the one for building and running the application for the first time is currently

```bash
rake developing:clean_rebuild_all
yarn start electron
```
Whereas the current working commands are:
```bash
rake build_dev                # build chipmunk (dev)
rake build_prod               # build chipmunk (prod)

rake run_dev                  # start chipmunk (dev)
rake run_prod                 # start chipmunk (prod)
``` 

I believe the rest of the command could be outdated too since there is no `developing` namespace in `rakefile.rb` anymore

**Comment by marcmo** [comment]
thanks for the issue! you are welcome to open a PR if you want ;)

**Comment by DmitryAstafyev** [comment]
@AmmarAbouZor thanks for report, that's true, we should update documentation in that part #1960

**Comment by AmmarAbouZor** [comment]
@marcmo @DmitryAstafyev I think I can create PR for it and update the contribution commands since I'm currently reading the rakefiles in the repo to enhance my ruby skills :+1:
