### ISSUE TITLE
Create a chipmunk cli tool for developers

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1966]
chipmunk has evolved to be more than a product, it's a platform + a specific use case.
we have long used rake for all developer related tasks.
especially building and re-building chipmunk is challenging.
we are a rust + typescript project and do not want to rely on ruby/rake on the developer side.
so we want to create a tool similar to the node-bindgen cli (https://github.com/infinyon/node-bindgen) that takes care of those tasks and replaces rake.
the tool should be implemented as a rust application

**Comment by AmmarAbouZor** [comment]
This is a great idea!
Would it be specific for chipmunk or for rust + typescript apps in general? if it's gonna have a general use I would suggest creating a separate repo for it so we can publish it to `crates.io` when it's done

**Comment by AmmarAbouZor** [comment]
I think this one is already done. Nice to see first issue I worked on again :grinning:
