### ISSUE TITLE
Create automated benchmarks for main usecases

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1993]
We need to track the performance for our main usecases:

- [x] search in text file
- [x] open dlt file
- [x] search in dlt file
- [x] startup measurements
- [ ] open 100 sessions for small files at the same time
- [ ] shutdown measurements

This should run in our own environment (custom github runners).
That way we can run the tests on our testdata that we store on the test-instance.

## usage

* should be integrated in build-system
* should be get executed by tester offline (not on github actions) or in relative constant CI environment

**Comment by itsmesamster** [comment]
_**Already Implemented :**_  
-  search in text file
-  open dlt file
-  search in dlt file

_**In progress :**_
-  startup measurements
-  shutdown measurements
-  open 50 sessions for small files at the same time

_**To be implemented :**_ 
Dmitry will create an issue for:
concat view: disable button "open as single" for more than 50 files
concat view: notify user with popup about opening as single tab more than 10 files
sys level (client) - prevent more than 50 tabs/session. Ask user close some tab with attempt to open +1 over 50 opened
rust level - return error on session-create-request if it's +1 over 50

**Comment by itsmesamster** [comment]
Completed with PR#2061
