### ISSUE TITLE
Incorrect view of UTF-16 with BOM

### ISSUE THREAD

**Issue by ikar49** [esrlabs/chipmunk#1996]
**Prerequisites**

affected version: 3.10.9

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

![image](https://github.com/esrlabs/chipmunk/assets/1428838/de830d17-b813-46ab-9961-3599b99dfa37)

But in selection this is correct:
![image](https://github.com/esrlabs/chipmunk/assets/1428838/6b6837e1-b4c8-4986-86fa-b1d81d159f7f)

I know that Chipmink [doesn't support encoding other than UTF-8](https://github.com/esrlabs/chipmunk/issues/1921), but this file only contains characters with the code 0-127, so I expect to see
```
????
?A?B?C?D
```
or something similar.

And as far as I can see, Chipmunk actually supports UTF-16-BOM, but with problems :)

**Steps to Reproduce**

Create file in UTF-16 with BOM

**Environment**

![image](https://github.com/esrlabs/chipmunk/assets/1428838/f44ede88-4f52-49a4-9931-aa16a8596616) ![image](https://github.com/esrlabs/chipmunk/assets/1428838/af74141e-86a2-488a-a7e2-25edf72c1ce1)

**Failure Logs**

Example of bad file:
[klwc-ext-2024-03-15-13-42-37.log](https://github.com/esrlabs/chipmunk/files/14615781/klwc-ext-2024-03-15-13-42-37.log)

**Comment by marcmo** [comment]
Hello @ikar49, thanks for reporting this issue!
Indeed, I can reproduce it with your example. We will take a look at it and try to swiftly resolve it!
