### ISSUE TITLE
Explore tantivy for indexing and searching multiple files

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#2013]
- [ ] explore architecture of tantivy
- [ ] create benchmark with 100 files with 100 MB
  - [ ] time to index everything
  - [ ] time to search for a filter
  - [ ] time to search for a regex

**Comment by itsmesamster** [comment]
Benchmarked with 1060 files ranging from 44 bytes to 2.9GB from various datasets and the total size of the files is ~ 32.5 GB.
Time to index everything - 44 minutes
Time to search term         - 6-12 sec
Time to search regex.      - 5-14 sec

Benchmarked with more than 5.1 million files ranging from 44 bytes to 2MB from various datasets and the total size of the files is ~ 11 GB.
Time to index everything - 4 hours 36 minutes
Time to search term         - 2-4 sec
Time to search regex.      - 0.3-4 sec

Benchmarked with 1 json file ranging and the total size of the files is ~ 8.9 GB.
Time to index everything - 16 sec
Time to search term         - 1-3 sec
Time to search regex.      - 0.1-0.4 sec

Benchmarked with 100 files of size 104 MB with same data and the total size of the files is ~ 10.3 GB.
Time to index everything - 30 sec
Time to search term         - 3-4 sec
Time to search regex.      - 0.1-1 sec

**Comment by itsmesamster** [comment]
Benchmarks done. Sample implementation will be added to https://github.com/esrlabs/chipmunk-research.
