### ISSUE TITLE
Update on MacOS seems not to install the correct architecture

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#2053]
steps to reproduce:
* I have an x86_64 version of chipmunk installed
* I update it
* all executable files (in the chipmunk.app bundle in `/Applications` are still `x86_64`

comparing to a freshly downloaded chipmunk for `arm64` the same files are of the correct architecture

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/1a7336f2-37f9-45a2-8012-10ee47ac6a6c">

**Comment by itsmesamster** [comment]
Issue has been fixed, the solution has been merged to the repository and will be available with release 3.12.10 onwards.
