### ISSUE TITLE
Disable CI Checks on Draft PRs

### ISSUE THREAD

**Issue by AmmarAbouZor** [esrlabs/chipmunk#2066]
It would be helpful to disable the CI checks for Pull Request while they are in the draft state, since they aren't that useful for a work-in-progress PRs.
There is no built-in option on GitHub for that, but we can achieve that by adding an [if statement to the CI jobs](https://stackoverflow.com/questions/68349031/only-run-actions-on-non-draft-pull-request).

**Comment by itsmesamster** [comment]
Implemented and merged to master
