### ISSUE TITLE
Include Build CLI integration tests in GitHub Action

### ISSUE THREAD

**Issue by AmmarAbouZor** [esrlabs/chipmunk#2075]
Build CLI tool has integration tests written as python scripts. These scripts should be used in a GitHub action which should run on PRs that may have an impact on the build CLI system.

* The GitHub Action should check if PRs (none-draft) have a special label on them to run automatically. It would be nice to have the opportunity to run them manually as well.

* It would be useful to insure that, the version of the tool has been increased on each PR as well.

* It could be useful to enforce changing to CHANGELLOG.md file once it's created on each PR as well.

**Comment by itsmesamster** [comment]
This has been implemented and the code has been merged to the master branch.
