### ISSUE TITLE
Release process for macOS needs to fail if the notarisation step does not return the status as Accepted.

### ISSUE THREAD

**Issue by itsmesamster** [esrlabs/chipmunk#2100]
We have moved away from electron based code-signing for macOS to a separate, manual code-signing process.

Once the code signing is completed and we submit the signed app to the notary tool, the notary tool runs a number of validations on the signed files within the app, and if everything is fine, the command execution status is returned as success and provides a response with status="Accepted".
If there are issues identified by the notary tool, the command execution status is returned as success but the notary tool provides a response with status="Invalid". In this case, the process needs to fail, so that it becomes evident that the entire code sign process has been unsuccessful.

**Comment by AmmarAbouZor** [comment]
Hi @itsmesamster, I remember that the status will be mentioned for each check which means that the word `Accepted` will be repeated and we can't look for that word only. 
I think the best solution it to look for the line with the final result. We can add this line to the configuration file and compare each line the output of the command to it. Finding this line will mean that the notarizing is accepted.
Therefore, I need to whole line at the end of the notarizing logs where the result is stated to put in the configuration file.
