### ISSUE TITLE
Support log entries spread across multiple files

### ISSUE THREAD

**Issue by elektronenhirn** [esrlabs/chipmunk#215]
# Prerequisites

I have log entries spread across multiple files:

```
messages
messages.0
messages.1
messages.2
messages.3
messages.4
messages.5
```

# Expected Behavior

It would be awesome if the logviewer could concatenate them into one single view. I would imagine a command line such as `logviewer --concat messages*` inside of the folder where the log files are stored.

Another option would be to offer a "open folder" button somewhere in the UI with the option to concat all files in a folder instead of opening them as indivial tabs.

Oli had the idea to support drag and drop too.

**Comment by marcmo** [comment]
should already be possible, but only with sorting logs by timestamp.
should we add a simple "just concatenate" option @elektronenhirn ?

**Comment by elektronenhirn** [comment]
If I remember my usecase right, sorting by timestamp would shuffle some lines, as each logfile corresponds to a lifecycle, and at the beginning of each lifecycle there is no valid time yet.
So adding a switch to toggle between merge and concat would be indeed great.
