### ISSUE TITLE
GitHub Action: Rust-Cache action failing silently

### ISSUE THREAD

**Issue by AmmarAbouZor** [esrlabs/chipmunk#2153]
The GitHub action to cache rust artifacts and binaries is failing currently without marking the job as failed.

Here is a [link for the logs on latest build](https://github.com/esrlabs/chipmunk/actions/runs/11934520246/job/33263804603#step:6:1) 

It would be helpful to find out if there is a way to mark the job as failing if it runs into such problems

**Comment by itsmesamster** [comment]
Issue has been resolved and merged to the master.
