### ISSUE TITLE
offer command line option to open chipmunk

### ISSUE THREAD

**Issue by elektronenhirn** [esrlabs/chipmunk#216]
Allow opening log file from command line

something like

`chipmunk <filepath>`

e.g. open up a logfile
installing could look like this:
![image](https://user-images.githubusercontent.com/99541/62627544-ddf30600-b929-11e9-9767-6b9da78ee95b.png)

**Comment by elektronenhirn** [comment]
@marcmo is there a way to prioritize this issue?

This also prevents proper integration into the "Open With" dialogs of Windows Explorer, Linux' Nautilus, eventually MacOs Finder...

**Comment by DmitryAstafyev** [comment]
I think it also can go forward with it #443

**Comment by marcmo** [comment]
@DmitryAstafyev can we adress this now?

**Comment by Deilan** [comment]
Sad to see this one won't happen :'(

**Comment by DmitryAstafyev** [comment]
> Sad to see this one won't happen :'(

Hello @Deilan, to make possible calling chipmunk via terminal you should install cli. 
- open chipmunk
- menu File/Instal CM Command Line Tool.
This procedure requires root/admin rights, but we do not plan to have an installer for chipmunk and would like to release only portable versions. That's why this feature has to be installed optionally.

**Comment by Deilan** [comment]
Hello @DmitryAstafyev, thanks for letting that happen!

I installed. Couldn't find any CLI usage guide. Could you please explain how to use it?

**Comment by DmitryAstafyev** [comment]
> Hello @DmitryAstafyev, thanks for letting that happen!
> 
> I installed. Couldn't find any CLI usage guide. Could you please explain how to use it?

Hello
It should be available via simple
```
> chipmunk file_name_to_be_opened
```

**Comment by fur-gan** [comment]
Hello @Deilan,
we have updated the documentation, you can now find a guide on how to use it here:

https://esrlabs.github.io/chipmunk-docs/book/01_usage/command_line

Note: The filename argument is optional and multiple files can be opened as well, which will all open their own tab

**Comment by Deilan** [comment]
@DmitryAstafyev @fur-gan Thank you very much for the information and the docs updates. Thanks to that I've managed to start using of `cm.exe`.

A couple of thoughts I think is worth to be voiced:
1. As far as I understand, `cm.exe` initially resides at `./resources/app/dist/compiled/apps/`. So launching `cm.exe` right from there without manual install is equivalent?
2. When one installs via "Install "cm" Command Line Tool", on Windows `cm.exe` is being copied to `$SystemRoot/System32`. It's a bit hacky, maybe modifying $PATH variable is enough?
