### ISSUE TITLE
replace color combinations for highlighting

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#288]
use:
![image](https://user-images.githubusercontent.com/99541/60350145-4366e500-99c3-11e9-94e0-9eca05ff0347.png)
![image](https://user-images.githubusercontent.com/99541/60350255-7b6e2800-99c3-11e9-88e6-574222746392.png)
![image](https://user-images.githubusercontent.com/99541/60380428-c7fa4780-9a45-11e9-8ccc-73d4c56c8259.png)
![image](https://user-images.githubusercontent.com/99541/60350418-c5efa480-99c3-11e9-8386-aa28bd80615d.png)
![image](https://user-images.githubusercontent.com/99541/60350473-e4ee3680-99c3-11e9-9be3-11700f2d674f.png)
![image](https://user-images.githubusercontent.com/99541/60350508-f9323380-99c3-11e9-97ce-d8d2521c38f5.png)
![image](https://user-images.githubusercontent.com/99541/60350564-1bc44c80-99c4-11e9-9879-8464ed5717d0.png)
![image](https://user-images.githubusercontent.com/99541/60350605-30084980-99c4-11e9-9221-edfb1f887e8b.png)
![image](https://user-images.githubusercontent.com/99541/60380370-e7dd3b80-9a44-11e9-8d3e-e67ace050358.png)
![image](https://user-images.githubusercontent.com/99541/60380393-31c62180-9a45-11e9-981d-e338dc5a6550.png)
![image](https://user-images.githubusercontent.com/99541/60380396-47d3e200-9a45-11e9-9a55-fe76c1b47233.png)
![image](https://user-images.githubusercontent.com/99541/60380403-5e7a3900-9a45-11e9-8100-6835f7fd8a31.png)
![image](https://user-images.githubusercontent.com/99541/60380469-7900e200-9a46-11e9-8875-27f291e9f83c.png)

**Comment by DmitryAstafyev** [comment]
In addition: 
* coloring of a match should be generated based on coloring of filter with some offset.
