### ISSUE TITLE
support adjustment of timestamps for part of logfile

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#309]
some logfiles show an invalid timestamp at the beginning until a valid time is available on the device that logs. (e.g. on android adb logs the logs at startup do not have a valid timestamp)
there should be an option for the indexer to correct the times
![image](https://user-images.githubusercontent.com/99541/60513000-5e449c80-9cd6-11e9-8b2a-bead054b9113.png)
![image](https://user-images.githubusercontent.com/99541/60513051-7a483e00-9cd6-11e9-949f-7d5948be2511.png)

**Comment by DmitryAstafyev** [comment]
I would close it as soon as we have already implementation of timestamp detecting
