### ISSUE TITLE
[plugin: processes]. Some commands don't display output

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#325]
# Prerequisites

affected version: 1.8.1

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
Any command should give output in main view (even from stderr)

# Current Behavior
For example command `which` doesn't give output in some cases

**Comment by fur-gan** [comment]
Plugin no longer supported
