### ISSUE TITLE
Add overall color indicators for search results etc.

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#328]
re-use vertical scroll bar to indicate current position & matches
![image](https://user-images.githubusercontent.com/99541/60675248-3000c180-9e7c-11e9-9240-148996665c54.png)

**Comment by DmitryAstafyev** [comment]
Maybe as the first implementation - without coloring "from" filters. Just one color for all matches.

**Comment by DmitryAstafyev** [comment]
closing this issue because basic support is done
For the next step: migration "inspector" of search results (which provides info about, which filter has much on which line) would be created another issue.
