### ISSUE TITLE
Process environment of the process plugin should be inherited from user

### ISSUE THREAD

**Issue by flxo** [esrlabs/chipmunk#344]
# Prerequisites

affected version:

make sure to check this before filing an issue:

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected Behavior

When executing a process with the process plugin environment should be inherited from the user running chipmunk.

# Current Behavior

A poor subset of environment is used.

## Steps to Reproduce

Run any command.

## Context

* Operating System: OSX

**Comment by DmitryAstafyev** [comment]
done with 1.20.13
