### ISSUE TITLE
Add a history accessible by Ctrl-p or up in the process plugin

### ISSUE THREAD

**Issue by flxo** [esrlabs/chipmunk#345]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected Behavior

The process plugin maintains a history of the commands executed.

# Current Behavior

There is no history in the process plugin. Commands have to be retyped every time. Very annoying since the commands currently require lots of env setup since #344.

In best case there would be a fuzzy search `fzf` like way to search the history of commands.

**Comment by DmitryAstafyev** [comment]
Implemented in scope of sidebar app - Shell
