### ISSUE TITLE
find a better project name/branding

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#354]
examples:
# log_pipe

![image](https://user-images.githubusercontent.com/99541/61450183-d22da880-a956-11e9-91c9-0ca166a76e65.png)
![image](https://user-images.githubusercontent.com/99541/61450219-e5407880-a956-11e9-8e6f-3cafdb3a0115.png)
![image](https://user-images.githubusercontent.com/99541/61450252-f38e9480-a956-11e9-8d0c-c8005f5f26d2.png)
![image](https://user-images.githubusercontent.com/99541/61450269-fbe6cf80-a956-11e9-94d6-aa500cb074be.png)
![image](https://user-images.githubusercontent.com/99541/61450317-15881700-a957-11e9-84f9-d6a9e51d1696.png)
![image](https://user-images.githubusercontent.com/99541/61450333-233d9c80-a957-11e9-8946-865b5e31c818.png)
![image](https://user-images.githubusercontent.com/99541/61450504-87f8f700-a957-11e9-81df-b873029e5812.png)
![image](https://user-images.githubusercontent.com/99541/61450612-bf67a380-a957-11e9-92fd-e7945b8688ab.png)
![image](https://user-images.githubusercontent.com/99541/61450650-d7d7be00-a957-11e9-90e6-3a686ed697e0.png)
![image](https://user-images.githubusercontent.com/99541/61450678-e625da00-a957-11e9-882c-9fbcaa46c786.png)

**Comment by DmitryAstafyev** [comment]
1.19.0 -> chipmunk
