### ISSUE TITLE
warn user when loading search filters that current filters will be dropped

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#386]
# Prerequisites

affected version: 1.16.4

# Expected Behavior

when loading a filter configuration, a user should be presented with a warning that the current filters will be deleted

# Current Behavior

no such warning

**Comment by DmitryAstafyev** [comment]
Probably some kind of dialog:
a. Current filters would be lost: continue / cancel
or
b. Current filters would be lost. Would you like to save it before?: Save / Do not save / cancel
or
c. Current filters would be lost. Would you like to save it before?: Save / Do not save / Merge / cancel (* merge is a feature, which never was requested)
or
d. ???
