### ISSUE TITLE
matches not shown in search when filters load

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#387]
# Prerequisites

affected version: 1.16.4

open some file -> load filters -> add another file: will not show matches of search results in result view
![7DB9EE5E-C236-45EB-A5EE-70D1035F8200](https://user-images.githubusercontent.com/99541/62281281-c6111300-b44d-11e9-85f7-0fe27b7050e1.png)
![5AA3D5A1-1539-4AF7-B65F-EE26557E4341](https://user-images.githubusercontent.com/99541/62281299-cf9a7b00-b44d-11e9-8c81-896b2297233a.png)

**Comment by DmitryAstafyev** [comment]
not reproducible with 2.x.x
