### ISSUE TITLE
copying with Cmd+C changes selection (in search result view)

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#401]
# Prerequisites

affected version: 1.16.7

# Expected Behavior
selection should stay the same

# Current Behavior

![image](https://user-images.githubusercontent.com/99541/62636302-94121c00-b939-11e9-9026-d36d7cac0764.png)
after executing it look like this (selection changed)
![image](https://user-images.githubusercontent.com/99541/62636378-b99f2580-b939-11e9-96d4-7db9f2b85ef0.png)

**Comment by DmitryAstafyev** [comment]
selection controller is fixed with 1.19.3
