### ISSUE TITLE
copying multiple lines will lose line endings

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#407]
# Prerequisites

affected version: 1.18.0

just try to select multiple rows
![image](https://user-images.githubusercontent.com/99541/62932549-a0c2c400-bdc0-11e9-86b1-c947c9675d7c.png)
copy with Cmd+C, then try to paste in a text editor. line endings are lost

**Comment by elektronenhirn** [comment]
I can confirm the bug under Ubuntu, too. Pretty annoying, as this breaks my usual workflow of inspecting traces and placing the relevant lines into a ticket.

**Comment by DmitryAstafyev** [comment]
closed with 1.19.3
with linux was found one more issue related to clipboard: https://github.com/esrlabs/chipmunk/issues/418
