### ISSUE TITLE
add about menu also on linux and windows version

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#409]
# Prerequisites

affected version: 1.18.0

on Mac OS, we get this about menu:
![image](https://user-images.githubusercontent.com/99541/63027461-4ce1d900-bead-11e9-8136-d8f6f245815b.png)

this is missing on linux (and possibly windows) which makes it harder to find out the version

**Comment by joboesr** [comment]
It´s also not there on Windows, but would be really helpful, especially with the automated updates.
