### ISSUE TITLE
When copying multiple lines on windows the line breaks and tabs are not copied

### ISSUE THREAD

**Issue by joboesr** [esrlabs/chipmunk#444]
# Prerequisites

affected version:
chipmunk@1.20.1-win64-portable

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
When selecting and copying (Ctrl-C) multiple lines the line breaks and tabs should be copied as well

# Current Behavior
After pasting there are no line breaks and tabs

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. Open a logfile, see sample attached [SampleForChipmunk.txt](https://github.com/esrlabs/chipmunk/files/3590158/SampleForChipmunk.txt)
2. Select more than one line
3. Copy (Ctrl-C)
4. Paste in editor, e.g. notepad++
5. Everything is one line

**Comment by DmitryAstafyev** [comment]
closed with 1.20.13
