### ISSUE TITLE
Automatically reload last saved filters

### ISSUE THREAD

**Issue by joboesr** [esrlabs/chipmunk#457]
Usually i have a set of filters which i use over multiple sessions. 

# Expected Behavior

It would be much easier if chipmunk would automatically load the most recent file on startup.
Alternatively a list of recent filter files in the search tab would make loading it easier (one-click). This option would be better for cases when there are multiple scenarios and the filters vary from each session.
Another approach could be to allow structuring filters and saving them all together in one file. The user could then disable / enable folders in the filter list.

# Current Behavior

I have to select the filters file manually in each session.

**Comment by marcmo** [comment]
will be solved with #873

**Comment by DmitryAstafyev** [comment]
Available since 2.14.x
