### ISSUE TITLE
Copy / paste: losing special symbols  

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#465]
# Prerequisites

affected version: 1.20.12

A copy of selection in view (or search) doesn't have special symbols like tabs, whitespaces. 
All such special symbols should be converted to HTML mnemonics before copy operation to allow browser correctly recognize it.

**Comment by MortronMeymo** [comment]
Probably this is also the cause why I cant copy xml type content from a log.
Example:
In log: Blah blah <test>Hello World</test> blub blub
After Copy&Paste: Blah blah Hello World blub blub
[ChipmunkExample.log](https://github.com/esrlabs/chipmunk/files/3609351/ChipmunkExample.log)

**Comment by DmitryAstafyev** [comment]
yes, @MortronMeymo obviously it's related. Thanks for your comment.

**Comment by DmitryAstafyev** [comment]
closed with 1.20.13
