### ISSUE TITLE
Allow opening log file from command line

### ISSUE THREAD

**Issue by MortronMeymo** [esrlabs/chipmunk#466]
# Prerequisites

affected version:

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
When called from the command line like:
`chipmunk <path_to_log_file1> <path_to_log_file2>`
Chipmunk should start and immediately open the specified log(s).

It would also be great to reduce the stdout spam...

# Current Behavior
Chipmunk starts but ignores the command line parameters.

## Context

* Operating System: Linux

**Comment by marcmo** [comment]
duplicate of #216
