### ISSUE TITLE
only allow 1 instance of chipmunk at the same time

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#469]
affected version: 1.20.13

using multiple instances of chipmunk is not stable

# Current Behavior
If a few instances are running:
* Filters are not applied
* No way to colorize the lines 
* Open dialog only offers files with the ending *.txt
## Steps to Reproduce
* Open at least two instances of chipmunk
* Try to do regular activities (search, storing filters, coloring)

## Context

* Operating System: Ubuntu 19.04

**Comment by elektronenhirn** [comment]
Here is my logfile:

[logviewer.log](https://github.com/esrlabs/chipmunk/files/3616424/logviewer.log)
