### ISSUE TITLE
add shell completions to the process plugin

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#481]
most shells enable completions (e.g. filenames)
would be nice to enable the same completions as the user gets in their shell
![image](https://user-images.githubusercontent.com/99541/66049053-f4cd6780-e52a-11e9-8b69-d73526e687ea.png)

**Comment by DmitryAstafyev** [comment]
since 2.15.x we have the `shell` tab. It has recent commands support. But terminal support was depricated.
