### ISSUE TITLE
overlapping markers not showing up correclty

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#488]
when I have a file that has several matches in 1 row like this:
![image](https://user-images.githubusercontent.com/99541/66201161-eb670b00-e6a2-11e9-8715-1971a9efe5b0.png)
then not all rows are correctly marked in the stacked view:
![image](https://user-images.githubusercontent.com/99541/66201209-17828c00-e6a3-11e9-9891-27df6f7da647.png)
what is also weird: the scroll bar and the greyed out area of the marker bar do not match when the window height is changed:
![image](https://user-images.githubusercontent.com/99541/66201303-531d5600-e6a3-11e9-844c-ab4639831977.png)
![image](https://user-images.githubusercontent.com/99541/66201327-5f091800-e6a3-11e9-84d9-f72ea6214b7c.png)
![image](https://user-images.githubusercontent.com/99541/66201335-67f9e980-e6a3-11e9-94e9-169649fca293.png)

**Comment by DmitryAstafyev** [comment]
not actual for chipmunk 3
