### ISSUE TITLE
Open search results in new tab

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#518]
# Prerequisites

affected version: 1.24.0

Would be great to have a button, which allows exporting search result from Tab A as the content of Tab B.

**Comment by marcmo** [comment]
not directly but almost:
in chipmunk 3 you can export all search results in a file:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/99541/219111324-19868232-3920-4166-9e32-f21aab584be6.png">
