### ISSUE TITLE
apply fibex description xml file after DLT file was opened

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#560]
currently, fibex description can only be assigned when opening

**Comment by vladirupanov** [comment]
I think this is rather low priority, given that everything else can be loaded/stored and the file can be reopened in seconds.

**Comment by DmitryAstafyev** [comment]
I would close it. In any way it "on the fly" attaching fibex-file means - reindexing the whole dlt-file again. From a performance point of view, it doesn't make any sense. It could be done for UDP/TCP connections, but it's already there (click "disconnect"; define fibex; click "connect" again)
Please reopen this issue, if I've understood the idea incorrectly.

**Comment by DmitryAstafyev** [comment]
BTW, we have suitable feature - reopen file (on file-tab context menu)
