### ISSUE TITLE
show Filter options when opening DLT files

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#564]
![image](https://user-images.githubusercontent.com/99541/70214178-3f41af00-173b-11ea-88fb-8dc3e1856206.png)

currently, we do not show the filter options when loading a DLT file. The user has to actively expand them to get access:
* The expansion should be automatic so users don't miss that option
* the button text should say "Fibex Description"

![image](https://user-images.githubusercontent.com/99541/70220211-7f5a5f00-1746-11ea-90b1-2dd8e62385a1.png)

**Comment by DmitryAstafyev** [comment]
Fixed.
