### ISSUE TITLE
option to save filters should be grayed out when no filters are present

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#567]
looks like:
![image](https://user-images.githubusercontent.com/99541/70216092-20ddb280-173f-11ea-930e-c7ece60de32b.png)

should look like:

![image](https://user-images.githubusercontent.com/99541/70216088-1de2c200-173f-11ea-81e1-cdaf4291699e.png)

**Comment by DmitryAstafyev** [comment]
no actual since 2.x.x
