### ISSUE TITLE
change position of filter for notifications

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#569]
currently, it is too easy to confuse this with the search view

![image](https://user-images.githubusercontent.com/99541/70217373-52f01400-1741-11ea-8406-f03bed11be1c.png)

should be placed on the right side like in vs code

![image](https://user-images.githubusercontent.com/99541/70217348-44096180-1741-11ea-98ec-01a6a942b3fc.png)

**Comment by DmitryAstafyev** [comment]
The notifications view will be redesigned to fit angular material lib.
