### ISSUE TITLE
fix keyboard shortcuts

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#574]
* Remove shortcut for open dlt file

windows:
what does work: Ctrl-B, j, k

what does not work: Ctrl-J, ?

mac:
does not work: CMD + J

jumping from to next bookmark does not select the next one but some other one

**Comment by DmitryAstafyev** [comment]
I cannot reproduce the issue on windows after basic fixing. So, I will close this issue. If someone will meet some issues on windows related to shortcuts, please, try to provide a way to reproduce it.
