### ISSUE TITLE
Chipmunk process blocks file access on Windows even after closing a tab

### ISSUE THREAD

**Issue by joboesr** [esrlabs/chipmunk#608]
# Prerequisites

affected version:

1.33
1.34

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

I can move or rename folders, at least after i closed the all related files in chipmunk again

# Current Behavior

Windows won´t let me rename or move a folder with a file which WAS or is opened by chipmunk, until chipmunk is closed
I can rename the file itself, but not rename or move the folder containing it, until i close chipmunk.

# Failure Information (for bugs)

## Steps to Reproduce

1. Open a file in chipmunk.
2. Try to rename or move its folder
3. Windows error message appears
![image](https://user-images.githubusercontent.com/33663717/70897968-04216480-1ff4-11ea-8341-94eaab163a16.png)

The behaviour stays even after i renamed the file.

## Context

* Operating System: Windows 10
* node version:
* npm version:

## Failure Logs

Process explorer shows that the handle is on the file:

![image](https://user-images.githubusercontent.com/33663717/70898027-23b88d00-1ff4-11ea-8a1a-f1fbdbd289cb.png)

**Comment by DmitryAstafyev** [comment]
confirm, it's reproducible on windows.
chipmunk's logs don't have any errors. Looks like it comes from an indexer

**Comment by DmitryAstafyev** [comment]
Logs of chipmunk
[chipmunk.launcher.log](https://github.com/esrlabs/chipmunk/files/3979344/chipmunk.launcher.log)
[chipmunk.log](https://github.com/esrlabs/chipmunk/files/3979345/chipmunk.log)
[chipmunk.indexer.log](https://github.com/esrlabs/chipmunk/files/3979346/chipmunk.indexer.log)

**Comment by DmitryAstafyev** [comment]
resolved 2.x.x
