### ISSUE TITLE
Possible memory leak - chipmunk doesn't shut down correctly

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#628]
After chipmunk is closed

![Screenshot 2020-01-03 at 16 50 51](https://user-images.githubusercontent.com/12843747/71733196-48609180-2e49-11ea-935e-1599f851912b.png)

Happens from time to time. Wasn't tested on windows and linux, only mac

**Comment by marcmo** [comment]
not reproducible
