### ISSUE TITLE
Text file not loaded correctly, problem while scrolling

### ISSUE THREAD

**Issue by attilastrba** [esrlabs/chipmunk#635]
I am trying to load 2 text file for log analysis.

affected version:
Version 1.34.0 (1.34.0)

# Expected Behavior
Once both the files are loaded I expect to be able to scroll in the file.

# Current Behavior
If I scroll around the file the lines will disappear and re-appear at the end of the file. See screenshot.
![chipmunkscrollproblem](https://user-images.githubusercontent.com/10559586/72144084-31b1c180-3398-11ea-9473-7be02c3f3c92.png)
 

# Failure Information (for bugs)
This seems to be a bug. 

## Steps to Reproduce
1. Open first text file 
2. Open second text file 
3. Switch to the first text file and scroll around

## Context

MacOS Catalina 10.15
$ node -v
v13.2.0
$ npm --version
6.13.1

**Comment by marcmo** [comment]
this is a bug. I cannot reproduce it though. could you please
1. check if it is reproducible in 1.36.x
2.if it is, provide us with the content of the ~/.chipmunk/chipmunk.indexer.log file and the offending files
thanks a lot!

**Comment by marcmo** [comment]
Hi @attilastrba , could you please try to reproduce it and send me the logs for it?

**Comment by attilastrba** [comment]
@marcmo I have tried to reproduce it with 1.36.x with the same files... I did the same steps, but unable to reproduce, thus closing ticket. I guess it was happening with some specific window/monitor settings in my macbook.
