### ISSUE TITLE
Minor: Undo after erase is not working

### ISSUE THREAD

**Issue by attilastrba** [esrlabs/chipmunk#636]
Once the erase button is pressed, the undo is not working. 

affected version:
Version 1.34.0 (1.34.0)

# Expected Behavior
Undo should work or the button should be disabled if it is not supposed to work in this context. 

# Current Behavior
By pressing undo the text is not restored. 

## Steps to Reproduce
1. Load a text file 
2. Press the erase button in the GUI 
3. Try to press COMMAND+Z or Undo in the menu, nothing happens

## Context
MacOS Catalina 10.15
$ node -v
v13.2.0
$ npm --version
6.13.1

**Comment by marcmo** [comment]
let's disable the undo button after erase. this is a rather heavy operation and keeping it on an undo stack is too expensive.

**Comment by marcmo** [comment]
closing this in favor of #660
