### ISSUE TITLE
rework dlt column formatting options

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#642]
![image](https://user-images.githubusercontent.com/99541/72323429-046f5700-36a9-11ea-95b8-37d9a85fff9f.png)

1.automatically select the entry of the column that was used to summon the settings (or by default select the first entry) and show the colors for it
2.rename `apply` to `ok` and close the settings dialog
3.close on `esc`
4. apply material style

**Comment by fur-gan** [comment]
I would suggest to make `esc` close the dialog and **cancel** the changes (as it is already implemented in https://github.com/esrlabs/chipmunk/issues/661)
`enter` should instead **apply** the change and close the window
