### ISSUE TITLE
improve dlt-stream udp settings

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#650]
1. add `required` tag to required fields
![image](https://user-images.githubusercontent.com/99541/72506196-b93c7c00-3841-11ea-8741-f8c31d2569c6.png)
2. validate input AFAP: 
* valid ip, 
* valid port
* validate that the address entered in multicast settings is indeed a multicast address
3. add checkbox next to Multicast settings that enable/disable all multicast settings
4. us outlined style for fields
![image](https://user-images.githubusercontent.com/99541/72506315-ee48ce80-3841-11ea-8171-2bab03da507e.png)

**Comment by DmitryAstafyev** [comment]
I am pretty sure it can be closed: https://github.com/esrlabs/chipmunk/releases/tag/2.13.1
