### ISSUE TITLE
Support global ENTER/ESC for dialogs

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#661]
In general, should be implemented default functionality for ENTER.
For example in dialogs like DLT-option by pressing ENTER file should be opened. 
Each dialog should have a default action by pressing ENTER.

ESC should always close dialog.

**Comment by fur-gan** [comment]
Maybe we should also add the functionality to close the popup if left-clicked outside of the dialog

**Comment by DmitryAstafyev** [comment]
> Maybe we should also add the functionality to close the popup if left-clicked outside of the dialog

Yes, it's a great idea.
