### ISSUE TITLE
Error while searching in serial stream

### ISSUE THREAD

**Issue by joboesr** [esrlabs/chipmunk#669]
# Prerequisites

affected version: 1.34

# Expected Behavior
Search works while streaming via serial port

# Current Behavior
Search didn´t work with error "Cannot to do a search due error: EPERM: operation not permitted, open 'C:\Users\H012311\.chipmunk\streams\1580121138842-3C3CD431-2C18-EB9B-53BE-173AF086273A.search'."
It worked again after restarting chipmunk

# Failure Information (for bugs)

## Steps to Reproduce

Unknown, it stopped working at some point and recovered when restarting chipmunk

## Context

* Operating System: Windows7
* node version:
* npm version:

## Failure Logs

see attached
![image (9)](https://user-images.githubusercontent.com/33663717/73181413-74ed8d80-4117-11ea-8d94-31a987796926.png)
[chipmunk.zip](https://github.com/esrlabs/chipmunk/files/4117459/chipmunk.zip)

**Comment by marcmo** [comment]
is fixed
