### ISSUE TITLE
xTerminal disappear

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#671]
# Prerequisites
chipmunk@1.37.0

# Expected Behavior
Show xTerminal upon click

# Current Behavior
Show blank box

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
open xTerminal
type command (e.g. ls) and press ENTER
click any other toolbar plugin (e.g. Search)
click xTerminal again

## Context

* Operating System: Windows 10
* node version: 10.16.3
* npm version: 6.9.0

**Comment by marcmo** [comment]
was related to broken build, not an issue
