### ISSUE TITLE
Copied DLT content becomes unreadable as raw text

### ISSUE THREAD

**Issue by elektronenhirn** [esrlabs/chipmunk#675]
# Prerequisites

affected version:
1.36.0

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
DLT Content is properly outlined in clipboard

# Current Behavior
Whitespaces/Formatting is dropped

# Failure Information (for bugs)

## Steps to Reproduce

I opened a .dlt file. In the Search Request window I had the filtered result (out of two search requests). I marked all the lines and copied them to the clipboard (to attach them to a Jira ticket).

I pasted them into vscode. While the filtered results are displayed like a table in chipmunk (with all the DLT columns), the columns are not splitted anymore in raw text. I would at least expect some separator, like a whitespace, between each column.

## Context

* Ubuntu 19.10

## Failure Logs

no failures shown

**Comment by elektronenhirn** [comment]
Cannot reproduce this anymore.

**Comment by DmitryAstafyev** [comment]
Was fixed. With 2.16.2 works as well
