### ISSUE TITLE
Improve handling a lot of incoming messages at once

### ISSUE THREAD

**Issue by ir210** [esrlabs/chipmunk#689]
# Prerequisites

affected version: master

make sure to check this before filing an issue:

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

When sending a lot of chunks to the main area, no `[2020-02-06T09:17:42.242Z][DEBUG][StreamFileWriter: 37F3EF15-9D6B-3953-D142-8D360C1630D4]: Task is postponed. Tasks in queue: 2` is printed to the console.

# Current Behavior

![Bildschirmfoto 2020-02-06 um 10 18 54](https://user-images.githubusercontent.com/354800/74823089-73724800-5306-11ea-884d-faa745b7fd54.png)

# Failure Information (for bugs)

ADB stores all logs it receives into some kind of buffer. When one runs `adb logcat`, ADB also takes all previously stored logs from this buffer before printing the new ones. Therefore, we see all prior logs as the result. That's the default behavior, it also has a command to clean this previous logs so logcat will only print new logs.

With this behavior, the ADB plugin has two options:

1. Do not clear these previous logs
2. Clear the previous logs

The problem with the second option is that it takes 1 or 2 seconds to do the cleanup. During this time, Chipmunk's UI does not do anything. It gives the impression that Chipmunks freezes for 1 or 2 seconds.

If we go with the first option, Chipmunk still has to wait 1 or 2 seconds (because it receives a lot of lines from the previous logs at the same time) but it shows the rectangles in the main area that notifies users that Chipmunk is busy preparing the logs. The only drawback is those logs in the console. But, this doesn't affect the users.

It would be better if we can improve the performance of the component that handles incoming messages from the plugins so that it can handle a lot of messages at once.

## Context

* Operating System: MacOS 10.15.2
* node version: 10.17.0
* npm version: 6.13.1

**Comment by DmitryAstafyev** [comment]
@ir210 Hello and thanks for this issue.
Could you please in addition say:
- which release of chipmunk did you use
- how did you start chipmunk (probably from a terminal)

Thanks in advance

**Comment by ir210** [comment]
@DmitryAstafyev, I just pulled and rebased from the master branch this morning and it still happens.

I start Chipmunk with:

`env CHIPMUNK_DEVELOPING_MODE=ON rake start`

Hmm... I don't know what happens when the development mode is not on. I will try it tomorrow.

**Comment by DmitryAstafyev** [comment]
@ir210 In developing mode maximum log-level will be set. So, it's okay you see in the terminal so many messages. You can use `export CHIPMUNK_DEV_LOGLEVEL=ERROR` to force the necessary log level and get rid of not important information.

But actually I believe, better use the [release](https://github.com/esrlabs/chipmunk/releases/tag/1.38.1) version of chipmunk for daily work.

**Comment by DmitryAstafyev** [comment]
For a moment, I switched such "repeated" logs into `ENV` level. Such logs will not be written into a chipmunk's log-file and it could also make performance a bit better.

**Comment by DmitryAstafyev** [comment]
In general, a queue controller is upgraded and optimized. Available since 2.16.2
