### ISSUE TITLE
allow to paste the content of the clipboard to a new tab

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#716]
`CMD` + `V` (or `ctrl` for windows and linux) should populate a new tab with the content of the clipboard.
can also be done via context menu in an empty tab or when there is no tab at all.
should also be added to the menu.
should not be enabled in tabs that already contain data.

**Comment by fur-gan** [comment]
How about `CMD/CTRL` + `SHIFT` + `V` to append the current tab in case you want to add something?

**Comment by DmitryAstafyev** [comment]
Looks like duplicate #495
