### ISSUE TITLE
double click on chart/filter should trigger "Show matches"

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#735]
(from context menu)

**Comment by DmitryAstafyev** [comment]
In addition:
- remove from the context menu - "activate / deactivate" for single
- rename "Activate/Decativate All" to "Select/Unselect All"
- rename "Activate except/Decativate except" to "Select except/Unselect except All"
- rename "Show matches" to "Make Active" (make active means put into toolbar into search)
