### ISSUE TITLE
when a chart is created with little data, the focused area cannot be changed ever again

### ISSUE THREAD

**Issue by coldgrnd** [esrlabs/chipmunk#741]
bug on resize of the chart area. If data in the session wasn't enough to activate scale-cursor, on resize scale-cursor doesn't appear/disappear correctly
![image](https://user-images.githubusercontent.com/99541/76970116-b0dcec00-692b-11ea-9804-11bfe7896b78.png)

**Comment by fur-gan** [comment]
About the reported bug:
Do you mean this? Is this what it looks like?
![image](https://user-images.githubusercontent.com/56543045/100459944-9c5e0f80-30c6-11eb-9474-7391b60b7731.png)
