### ISSUE TITLE
when merging files, no matches are shown in preview

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#746]
that makes it hard to get the date expression correct 

![image](https://user-images.githubusercontent.com/99541/77226185-b1b58e00-6b76-11ea-936c-49441b1536ea.png)

use color codes to show different match groups similar to this
![image](https://user-images.githubusercontent.com/99541/79724305-95c51980-82e7-11ea-8d56-070096993f01.png)
regex in example (https://regex101.com/):
```
(?P<Y>[0-2]\d{3})-(?P<m>(0?\d|1[0-2]))-(?P<d>([0-2]\d|3[01]))\s?(?P<H>(0?\d|1\d|2[0-3])):(?P<M>[0-5]\d):(?P<S>[0-5]\d)\.(?P<millis>\d+)
```
test-string in example: `2019-07-14 15:24:10.000759 UTC`

**Comment by DmitryAstafyev** [comment]
This issue depends on #775
