### ISSUE TITLE
macOS Catalina: Can't open chipmunk from Finder's context menu, can't open a file via drag&drop

### ISSUE THREAD

**Issue by mh-** [esrlabs/chipmunk#766]
**Prerequisites**

affected version:
Version: 2.1.2
Electron: 8.1.0
Electron Rebuild: 1.10.0
ToolKit: 1.0.3
IPC: 0.0.42
Chipmunk Material: 0.0.1
Angular: 9.0.6
Angular Material: 9.1.3

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

What did not work as expected?
a) I want to be able to open a .log file from the macOS Finder with chipmunk. But when I try to configure that, chipmunk is not a recommended app for this type of file, and when I force macOS to do it, chipmunk opens up but doesn't load the file.
b) I want to drag and drop a .log file from the macOS Finder to chipmunk, but then chipmunk doesn't open it.

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.
a) 
- right-click on a .log file in Finder, select "open with" -> "other..."
- switch from "recommended apps" to "all apps" - this shouldn't be necessary
- select chipmunk
-> chipmunk opens, but the .log file is not opened

b)
- drag and drop a .log file into chipmunk
-> the file is not opened

**Environment**

version info from chipmunk's about menu
(see above)
macOS Catalina 10.15.3

**Failure Logs**

Please include any relevant log snippets or files here.
(if you tell me where chipmunk stores its logs, I'll attach them.)

**Comment by marcmo** [comment]
Hi @mh- 
thanks for reporting this issue! the "open with" is not yet available and does not work...but it's a good idea!
what is strange is that you cannot drag & drop files into chipmunk.
can you open files at all?
logs can be found in `~/.chipmunk/chipmunk.indexer.log`
if possible please attach them.

**Comment by mh-** [comment]
Tried again with release 2.3.1.
Drag & drop worked.

**Comment by DmitryAstafyev** [comment]
@mh- Thanks for feedback!
