### ISSUE TITLE
Right click -> Show row does not work on first try

### ISSUE THREAD

**Issue by MortronMeymo** [esrlabs/chipmunk#769]
**Prerequisites**

affected version: latest

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

When selecting a line and right clicking and choosing "Show row" the details view still shows the old selection. Redoing the action a second time fixes it.

**Steps to Reproduce**
Right click a line and choose show row. The first time this always works, because there is nothing yet in the details view.
Right click on a different line and choose show row. The details view still shows the old row.

**Environment**
Version: 2.1.2
Electron: 8.1.0
Electron Rebuild: 1.10.0
ToolKit: 1.0.3
IPC: 0.0.42
Chipmunk Material: 0.0.1
Angular: 9.0.6
Angular Material: 9.1.3

**Failure Logs**
Seams to happen more often if rows include xml.

**Comment by marcmo** [comment]
@MortronMeymo do you mean this context menu?
![image](https://user-images.githubusercontent.com/99541/78889882-db225500-7a64-11ea-896e-d2651e41f1ba.png)
does it only happen for certain file types?
would be great if you have an example file that gives you this problem.

**Comment by DmitryAstafyev** [comment]
Thanks for this report. Confirm, I can reproduce it

**Comment by MortronMeymo** [comment]
@marcmo Yes thats the menu I mean. I can provide a file but not publicly, though I'm not sure that is still needed if @DmitryAstafyev can reproduce the issue.
