### ISSUE TITLE
Reverse-opening file

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#773]
**Prerequisites**

affected version: 2.x

make sure to check this before filing an issue:

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**
It would be useful to have an option (on file opening): reverse.
If the option is active: the file is opening from the end to begin.

**More Information**
In some cases, developers are interested in logs, which "happened now", but if log file quite big, developers have to wait some time to let indexing be finished and read logs from the end to the beginning. Reversed logs, would be more comfortable from this point of view because:
- no need to wait for finishing of indexing
- regular reading (from beginning to end)

**Comment by marcmo** [comment]
won't implement
