### ISSUE TITLE
Limit zipped log size

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#796]
In the `About` tab we offer to store the logs. These logs should not take everything but limit the size of the files, only taking at most 10MB unpacked log data. (the last 10MB)

**Comment by DmitryAstafyev** [comment]
Limit for chipmunk log file is added (`CMaxLogFileSize = 20 * 1024 * 1024`). Size is checked with each start of chipmunk, well it can be during session file will has size out of that limits.
