### ISSUE TITLE
Allow more than one multicast group in live DLT reception configuration

### ISSUE THREAD

**Issue by vladirupanov** [esrlabs/chipmunk#803]
**In some projects DLT is sent via same link over different multicast groups**

affected version:

make sure to check this before filing an issue:

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**

Specify more than one multicast group for DLT live reception.

**Potential Workaround**

Allowing multiple live streams -- this comes with higher resource consumption.

**More Information**

here you can supply screenshots or just add more details

**Comment by vladirupanov** [comment]
Asking once again to prioritize this issue. 
It is important to catch up with live measurements for users to be able to use many handy features live (and help improve robustness and performance)!

**Comment by DmitryAstafyev** [comment]
https://github.com/esrlabs/chipmunk/releases/tag/2.13.0
