### ISSUE TITLE
No visible settings for serial connection if list of serial devices is too long

### ISSUE THREAD

**Issue by inorick** [esrlabs/chipmunk#816]
**Prerequisites**

affected version:
Version: 2.2.0
Electron: 8.1.0
Electron Rebuild: 1.10.0
ToolKit: 1.0.3
IPC: 0.0.42
Chipmunk Material: 0.0.1
Angular: 9.0.6
Angular Material: 9.1.3

chipmunk-serial-plugin@1.0.1

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

The settings of a new serial connection are not reachable if the list of available serial connections is very long.

**Steps to Reproduce**

1. Install serial plugin
2. Add 'Serial' side tab
3. Add connection
4. See popup (attached)

**Environment**

Fedora Linux 32

**Failure Logs**

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/27500920/83849660-0b5a3d00-a710-11ea-8a45-9b3bfb207dc9.png)
![image](https://user-images.githubusercontent.com/27500920/83849704-19a85900-a710-11ea-89f0-a5b967355c6f.png)

**Comment by marcmo** [comment]
this is still an old version of the plugin, we will check to see why the new version was not installed

**Comment by inorick** [comment]
I also see the following errors in notifications after the popup opens:
![image](https://user-images.githubusercontent.com/27500920/83850540-5f195600-a711-11ea-9c81-0bad4a468665.png)

**Comment by DmitryAstafyev** [comment]
no actual since `2.3.x`
