### ISSUE TITLE
Add support for time measurements

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#821]
this could look like:
1. go to "time-measurement mode"
2. here we detect and annotate all timestamps found in the lines on screen
![image](https://user-images.githubusercontent.com/99541/84043866-1b3f7e80-a9a7-11ea-8101-01215ea9e095.png)
3. one timestamp has to be selected
![image](https://user-images.githubusercontent.com/99541/84043966-3c07d400-a9a7-11ea-9c7b-2e829ff08816.png)
4. Drag down line to another timestamp
![image](https://user-images.githubusercontent.com/99541/84044664-2515b180-a9a8-11ea-9fef-195df4823b6c.png)
5. calculate the time difference

**Comment by DmitryAstafyev** [comment]
added with `2.4.1`
