### ISSUE TITLE
Chipmunk not closing properly

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#826]
**Prerequisites**

affected version: 2.3.1

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

What did not work as expected?
Chipmunk is not closed properly after deleting the **.chipmunk** and running it for the first time.

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

Remove the **.chipmunk** folder. (e.g `rm -rf .chipmunk`)
Start Chipmunk. `rake start`
Close Chipmunk.

**Comment by DmitryAstafyev** [comment]
It's relevant only for developing mode (starting with `rake dev` or `npm run electron`), because in developing mode chipmunk starts without launcher.
