### ISSUE TITLE
Support to show parsed timestamps in local time

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#906]
When we have timestamps for the log entries, DLT specifies them in UTC.
To make it easier to read a log file, it should be possible to convert them to local times similar as in Wireshark
![image](https://user-images.githubusercontent.com/99541/94239346-f1887400-ff11-11ea-821e-b09320eca595.png)

**Comment by DmitryAstafyev** [comment]
related #1169 and closed as soon as support of timezones for DLT has been added
