### ISSUE TITLE
Provide access to file content without building a full index-file

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#911]
When viewing a file, chipmunk currently creates a textual representation of the same file that contains annotations used by the frontend. This is fine for small files but is overhead when dealing with large files since the file practically duplicated.

In our new approach, the frontend only asks the native part for exactly the part of the file that should be rendered.

In effect, the performance to open a large file should be vastly improved.

**Comment by DmitryAstafyev** [comment]
not relevant any more and covered with grabber branch
