### ISSUE TITLE
Unable to set timestamp format for merge

### ISSUE THREAD

**Issue by tank0226** [esrlabs/chipmunk#915]
**Prerequisites**

affected version: 2.7.2

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

Entered correct timestamp format in the merging tab and clicked apply. Circular progress/activity indicator appear on apply button but nothing happens.

**Steps to Reproduce**

1. Drag and drop Haproxy logs and Nginx error log and click 'Merge'. Samples of the two logs provided below.

`Oct  1 03:34:22 localhost haproxy[49419]: 192.168.1.1:10544 [01/Oct/2020:03:34:22.106] www-https~ www-backend/www-1 0/0/2/13/15 200 386 - - ---- 2/2/1/1/0 0/0 {} {close} "GET /actuator/health HTTP/1.1"`

`2020/09/30 16:16:11 [error] 48834#48834: *272166595 open() "/usr/local/openresty/nginx/html/.well-known/dnt-policy.txt" failed (2: No such file or directory), client: 192.168.2.1, server: api.example.com, request: "GET /.well-known/dnt-policy.txt HTTP/1.1", host: "api.example.com"`

2. Timestamp detected correctly as DD/MMM/YYYY:hh:mm:ss for Nginx error log

3. Timestamp not detected for Haproxy logs with error "MM/DD/yy hh:mm:ss did not match in file"

4. Enter correct timestamp format YYYY/MM/DD hh:mm:ss and click apply.

**Environment**

Version: 2.7.2
Platform: win32(x64) / Windows_NT / 10.0.18362
Electron: 9.1.0
Electron Rebuild: 1.11.0
ToolKit: 1.2.15
IPC: 0.0.51
Chipmunk Material: 1.0.9
Angular: 9.0.6
Angular Material: 9.1.3

**Failure Logs**

[chipmunk.log](https://github.com/esrlabs/chipmunk/files/5321379/chipmunk.log)
[developer-console.log](https://github.com/esrlabs/chipmunk/files/5321381/developer-console.log)

**Comment by DmitryAstafyev** [comment]
not actual for chipmunk 3
