### ISSUE TITLE
Datetime format detection

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#916]
**Prerequisites**

affected version: 2.7.2

All stuff related to DateTime manipulations: merge and time measurement needs to be adjusted:
- add support for more regular formats, especially for months (`MM`, `MMM`, `m` etc.)
- add support of datetime in any place of row (not only in the beginning of the row)
- to detect DateTime format should be used next 3 ways:
1. Attempt to detect DateTime format automatically (already implemented)
2. Normal mode: Allow user to define format using format definitions (like `DD/MM/YYYY` etc).
3. Expert mode: Allow user to define format using grouped regular expression 

Related: 
#915

**Comment by MarkJonas** [comment]
It would be awesome if the default date format of systemd's journalctl output could be supported.

Example: `Sep 30 12:42:14 machine_name process_name[384]:  log output of process here`

More details on additional journalctl date format can be found in https://opensource.com/article/20/8/journals-systemd (look for "_journalctl time and date formats_").

**Comment by DmitryAstafyev** [comment]
not actual for chipmunk 3
