### ISSUE TITLE
Error when loading filters

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#917]
make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

Load filters by either selecting recent of from the file systems cause an error.

**Steps to Reproduce**

Open sidebar
Load filters / Load recent filters

**Failure Logs**

`Uncaught ObjectUnsubscribedErrorImpl {message: "object unsubscribed", name: "ObjectUnsubscribedError"}`

**Comment by DmitryAstafyev** [comment]
This is because the library `chipmunk-client-material` was updated and the new version of `DynamicComponent` isn't compatible to master version of `client.core`. I did pull request #919  which switch it to version `1.2.1` of `chipmunk-client-material`

**Comment by DmitryAstafyev** [comment]
@fur-gan if this bug isn't related to the production/master version, let's close an issue
