### ISSUE TITLE
Elements of sidebar not clickable

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#918]
make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

Cannot interact with elements on the sidebar that are on the height of the bin.

**Steps to Reproduce**

Create/Load a few filters so the `Manage` component is not visible
Scroll down and try to click `Load` or `Recent`

**Comment by DmitryAstafyev** [comment]
Probably also related to #919 . See comments above #917

**Comment by DmitryAstafyev** [comment]
@fur-gan please verify this bug for the production version. If it isn't related, let's close it
