### ISSUE TITLE
Support concat for DLT traces

### ISSUE THREAD

**Issue by MortronMeymo** [esrlabs/chipmunk#943]
Currently when trying to open multiple DLT traces via concat they are opened as text files and not as DLT files. Since some tools automatically split traces into smaller files (since said tools are too slow with large files) it would really help to have this feature.

**Comment by vladirupanov** [comment]
I can only second the mentioned enhancement. we also suffer from files being cut into 100MB-chunks, and it is not very meaningful to reapply the same filters N times to analyse a run

**Comment by DmitryAstafyev** [comment]
Concat introduced for DLT with chipmunk 3
