### ISSUE TITLE
Provide a way to specify where session files are stored

### ISSUE THREAD

**Issue by edibleparts** [esrlabs/chipmunk#986]
**Prerequisites**

affected version:
2.10

make sure to check this before filing an issue:

- [ x] I am running the latest version
- [ x] I checked to make sure that this issue has not already been filed

**Describe the issue**

What did not work as expected?

things work, but hiccup when disk quota exceeded in my home directory.  
[in large enterprise, home directory is a remote mount, and has a size quota outside of user control. User has local storage. Once home quota is reached, new files are not created, and on command line, error message shown "disk quota is reached"]
Apparently chipmunk creates search data, probably index in home dir. 
Once quota was reached, search tab misbehaved: content disappeared. Luckily notification tab shows error:
"Cannot to do a search due error: Unknown sustem error -122: Unknown system error -122, open 
'/home/ep/.chipmunk/streams/1607712240180-1DB2FECB-10E4-49A3-CA60-116947F761F6.search'

Few things:
1) [must] There must be a way to override this with a user-chosen directory, and it preferably should be exposed in GUI, and/or, at least in start up environment. Perhaps this functionality already, but I don't see it. Can be as simple as environment variable.

2) [nice to have] electron creates huge .cache files in home, but I suppose this is outside of chipmunk purview.  But chipmunk .cache space should be managed in gui, ideally. At least as in web browser, there should be a quick way to clear cache.

3) [nice to have] 
nitpick#1  better wording: "Search failed. System error code:-122 unknown error ......." 
nitpick#2 it would be nice if Clipboard Copy would work in notification window, so that error can be copied). 
nitpick#3 error should be more prominent - displayed either as popup, or in search panel itself. As it is I did not noticed it at first, it just stopped working, and restart did not help.

**Steps to Reproduce**
I don't know a good way to emulate home quota, make .cache readonly, perhaps?

**Environment**

Version: 2.10.0
Platform: linux(x64) / Linux
Electron: 10.1.5
Electron Rebuild: 2.3.2
ToolKit: 1.3.13
IPC: 0.0.51
Chipmunk Material: 1.2.5
Angular: 9.0.6
Angular Material: 9.1.3

**Failure Logs**

Please include any relevant log snippets or files here.

**Comment by edibleparts** [comment]
I forgot to mention that chipmunk installed in local storage (/scratch/ep/chipmunk/....) . .cache was created in remote /home/ep.

**Comment by marcmo** [comment]
Hi @edibleparts, thanks for reporting this! This is indeed something we never heard before but it makes sense to allow the user to define the directories that are used for session files.
BTW we are currently working on an on-the-fly indexing feature that will allow us to get rid of a lot of intermediary data currently used.
br
